name: real_image
image_shape: [3, 240, 320 ] # 最后经过处理输出的图像shape
dataset_path: /home/wxn/Projects/diffusion_policy/data/my_data

shape_meta: &shape_meta
  obs:
    camera_0: 
      shape: ${task.image_shape}
      type: rgb
    robot_eef_pose:
      shape: [8]
      type: low_dim
  action:
    shape: [8]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_pick_and_place_image_dataset.RealPickAndPlaceImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False
